@startuml
title WarmHouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

Person(user, "Пользователь", "Пользователь умного дома")
Person(admin, "Администратор", "Администратор умного дома")
System(WarmHouse, "Теплый дом", "Система управления микроклиматом в помещениях")

System_Boundary(WarmHouse, "Тёплый дом") {

  Boundary(ЛК, "Личный кабинет") {
    Container(apigateway, "API Gateway", "Kong", "IAM, RL, Reverse Proxy")  
    Container(WebApp, "Веб-приложение", "TS, React", "ЛК Пользователя")  
    Container(BFF, "BFF", "Java", "API для фронта")  
  }

  Boundary(Устройства, "Устройства") {
    Container(Devices, "Управление устройствами", "Java", "Регистрация устройств, метрики, команды")
    ContainerQueue(MessageBroker, "MessageBroker", "MQTT", "Шина обмена сообщениями с устройствами")
    ContainerDb(DevicesDB, "DevicesDB", "MongoDB", "Хранение информации об устройствах")
    ContainerDb(MetricsDB, "MetricsDB", "CassandraDB", "Хранение показаний с измерительных приборов")
  }

  Boundary(Пользователи, "Пользователи") {
    Container(Users, "Управление пользователями", "Java", "Регистрация пользователей, аутентификация, авторизация")
    ContainerDb(UsersDB, "UsersDB", "PostgreSQL", "Регистрация устройств, метрики, команды")
  }

  Boundary(Биллинг, "Биллинг") {
    Container(Billing, "Биллинг сервис", "Java", "Управление платежами и подписками")
    ContainerDb(BillingDB, "BillingDB", "PostgreSQL", "Хранение платежных данных и транзакций")
  }

  Boundary(Эксплуатация, "Эксплуатация") {
    Container(Operations, "Сервис эксплуатации", "Java", "Управление техническим обслуживанием")
    ContainerDb(OperationsDB, "OperationsDB", "PostgreSQL", "Хранение данных по ТО и инцидентам")
  }
}

System_Ext(controllers, "Внешние устройства", "Управляемые отопительные приборы")
System_Ext(sensors, "Внешние датчики", "Датчики температуры")
System_Ext(payment_providers, "Платежные системы", "Внешние процессинговые сервисы")

Rel(BFF, Users, "")
Rel(BFF, Devices, "")    
Rel(BFF, Billing, "")
Rel(BFF, Operations, "")
Rel(user, apigateway, "Работа в ЛК пользователя")
Rel(admin, apigateway, "Работа в ЛК администратора")    
Rel(apigateway, WebApp, "")    
Rel(apigateway, BFF, "")    
Rel(apigateway, Users, "IAM")    
Rel(Users, UsersDB, "Uses", "sync, JDBC")

Rel(Devices, DevicesDB, "Uses", "sync, JDBC")
Rel(Devices, MetricsDB, "Uses", "sync, JDBC")

Rel(Billing, BillingDB, "Uses", "sync, JDBC")
Rel(Operations, OperationsDB, "Uses", "sync, JDBC")
Rel(Billing, Users, "GET", "sync, HTTP")
Rel(Billing, Devices, "GET", "sync, HTTP")
Rel(Billing, payment_providers, "GET/POST", "sync, HTTP")

Rel(sensors, MessageBroker, "push показания")
Rel(MessageBroker, controllers, "push команды")
Rel(MessageBroker, Devices, "push показания")
Rel(Devices, MessageBroker, "push команды")
@enduml